### ISSUE TITLE
Shadowing `require('utils')`

### ISSUE THREAD

**Issue by luiz00martins** [jeff-dh/expJABS.nvim#1]
I'm currently not able to test the changes made from [#39](https://github.com/matbme/JABS.nvim/issues/39), as the expJABS branch shadows `require('utils')` which makes it incompatible with my configs (as they already use such call).

It'd be nice if it used `require('jabs.utils')`, or something similar.

**Comment by jeff-dh** [comment]
Hey,
sorry I just noticed this issue right now (I didn't watch all activity here) sorry!

I'll have a look at it soon.

**Comment by jeff-dh** [comment]
Ouh, didn't want to automatically close this issue, but I commited something that hopefully fixes your issue, could you verify that it's working (for you)?

**Comment by luiz00martins** [comment]
@jeff-dh can confirm, it does not shadow anymore. Thanks for the fix!
