### ISSUE TITLE
[Feature Request] Set `filetype`

### ISSUE THREAD

**Issue by luiz00martins** [jeff-dh/expJABS.nvim#2]
It seems like the JABS window sets its file name, but not its `filetype`.

I use the [`winbar`](https://github.com/fgheng/winbar.nvim) plugin, and you can exclude the winbar from appearing in the window by `filetype`. I do this for `terminal` for example, to not show the filetype. Without it, an ugly winbar gets displayed at the top with the "file name" (`expJABS`, `expJABS:help`, etc):

![image](https://user-images.githubusercontent.com/43142209/216374679-22716f09-24d5-411b-9479-9fc5d8f9f2e3.png)

It would be nice it the JABS windows had a distinct filetype.

**Comment by jeff-dh** [comment]
done....... (?)

can you verify that it's working?

**Comment by luiz00martins** [comment]
It is :)

Thank you
